#:schema https://mise.jdx.dev/schema/mise.json

min_version = "2024.11.1"

[env]
_.path = ["{{config_root}}/node_modules/.bin"]

[settings]
idiomatic_version_file_enable_tools = ["node", "pnpm"]

[settings.npm]
package_manager = "pnpm"
