import type { Metadata } from 'next';

import './global.css';

export const metadata: Metadata = {
  description: 'Generated by create-nx-workspace',
  title: 'Welcome to web',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
